[package]
name = "mkdata-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
csv = { version = "1.3.0", optional = true }
fake = "2.10.0"
thiserror = "1.0.64"

[features]
default = ["csv"]
full = ["csv"]
csv = ["dep:csv"]
